// Auto-generated list of products that allow decimal quantities
export const SPLIT_PRODUCTS = new Set([
  "Green Chilli",
  "Garlic (Big)",
  "Garlic (Small)",
  "Pepper Loose No.1",
  "Cumin Loose No.1",
  "Mustard Seeds",
  "Thuvaram Paruppu No.1",
  "Kadalai Paruppu No.1",
  "Pasi Paruppu No.1",
  "Dried Peas Dal",
  "Ulundu Paruppu 1",
  "Biryani Rice",
  "Biryani Rice (Chappi variety)",
  "Unit Rice (Brand)",
  "Sea Moss (Agar)",
  "Bay Leaf",
  "Mace (Javitri)",
  "Nutmeg",
  "Cinnamon (Big)",
  "Star Anise",
  "Cloves",
  "Cardamom No.1",
  "Groundnut (Uppu Kadalai)",
  "Groundnut (Peanut)",
  "Sugar No.1",
  "Maida (Refined Flour) No.1",
]);
